package main

type CPUCharacter struct {
	ID               string  `json:"id"`
	Name             string  `json:"name"`
	Desc             string  `json:"desc"`
	PitchSpeedMod    float64 `json:"pitchSpeedMod"`
	StrikeRate       float64 `json:"strikeRate"`
	SwingAtStrike    float64 `json:"swingAtStrike"`
	SwingAtBall      float64 `json:"swingAtBall"`
	CPUMissRate      float64 `json:"cpuMissRate"`
	SawNoise         bool    `json:"sawNoise,omitempty"`
	Wobble           bool    `json:"wobble,omitempty"`
	ExtremePan       bool    `json:"extremePan,omitempty"`
	CornersOnly      bool    `json:"cornersOnly,omitempty"`
	AnnoyingChangeup bool    `json:"annoyingChangeup,omitempty"`
	LowPitchesOnly   bool    `json:"lowPitchesOnly,omitempty"`
	Unpredictable    bool    `json:"unpredictable,omitempty"`
	Rhythmic         bool    `json:"rhythmic,omitempty"`
	ScatterPanner    bool    `json:"scatterPanner,omitempty"`
	RageMode         bool    `json:"rageMode,omitempty"`
	FlutterSound     bool    `json:"flutterSound,omitempty"`
	HeavySleep       bool    `json:"heavySleep,omitempty"`
	ClingIn          bool    `json:"clingIn,omitempty"`
	CryBaby          bool    `json:"cryBaby,omitempty"`
	RushedWindup     bool    `json:"rushedWindup,omitempty"`
	SweetZone        bool    `json:"sweetZone,omitempty"`
	SnoopyPouch      bool    `json:"snoopyPouch,omitempty"`
	SpendAll         bool    `json:"spendAll,omitempty"`
	Glare            bool    `json:"glare,omitempty"`
	GrumbleM         bool    `json:"grumbleM,omitempty"`
	HeavyL           bool    `json:"heavyL,omitempty"`
	PinkAura         bool    `json:"pinkAura,omitempty"`
	FlavorText       string  `json:"flavorText"`
	PitchText        string  `json:"pitchText"`
}

var CPU_CHARACTERS = []CPUCharacter{
	{
		ID:            "kikiriki",
		Name:          "木切り機（キーキリキ）",
		Desc:          "近所でいつも木を切っているうるさい機械。せっかちで大雑把。",
		PitchSpeedMod: 0.8,
		StrikeRate:    0.75,
		SwingAtStrike: 0.90,
		SwingAtBall:   0.65,
		CPUMissRate:   0.30,
		SawNoise:      true,
		FlavorText:    "ギギギギギ！とうるさい音を立てながら大雑把にスイングした！",
		PitchText:     "ギギギギギ！とチェンソーのような爆音を立てて投げました！",
	},
	{
		ID:            "kayui",
		Name:          "痒い星人",
		Desc:          "全身のそこら中を痒くして、プレイヤーの集中力をかき乱してくる。",
		PitchSpeedMod: 1.0,
		StrikeRate:    0.55,
		SwingAtStrike: 0.75,
		SwingAtBall:   0.35,
		CPUMissRate:   0.25,
		Wobble:        true,
		FlavorText:    "全身をボリボリ掻きむしりながらスイングした！",
		PitchText:     "体中を掻きながら、軌道が痒そうにうねるボールを投げました！",
	},
	{
		ID:            "maigo",
		Name:          "迷子星人",
		Desc:          "至る所で迷子にさせようとする。球の軌道も迷子になりがち。",
		PitchSpeedMod: 1.15,
		StrikeRate:    0.45,
		SwingAtStrike: 0.70,
		SwingAtBall:   0.45,
		CPUMissRate:   0.30,
		ExtremePan:    true,
		FlavorText:    "ベースがどこか分からなそうな様子で迷子スイング！",
		PitchText:     "ボール自身が方向を見失ったかのような迷子カーブを投げました！",
	},
	{
		ID:            "hippari",
		Name:          "引っ張り星人",
		Desc:          "無理矢理エレベーター（外角）に連れて行こうとする。打球も引っ張る。",
		PitchSpeedMod: 1.0,
		StrikeRate:    0.50,
		SwingAtStrike: 0.85,
		SwingAtBall:   0.30,
		CPUMissRate:   0.20,
		CornersOnly:   true,
		FlavorText:    "強引にレフト方向へ引っ張るスイング！",
		PitchText:     "無理矢理外角エレベーターへ連れていくようなコースに投げました！",
	},
	{
		ID:               "iiiiiiiii",
		Name:             "イイイイイイイイイ星人",
		Desc:             "仕事中に突然現れ、自分をいやぁぁな気持ちにさせる。嫌がらせが得意。",
		PitchSpeedMod:    1.3,
		StrikeRate:       0.40,
		SwingAtStrike:    0.80,
		SwingAtBall:      0.10,
		CPUMissRate:      0.15,
		AnnoyingChangeup: true,
		FlavorText:       "こちらの嫌がるタイミングをじっくり見極めてスイングしてきた！",
		PitchText:        "嫌〜な沈み方をする超遅球を投げました！",
	},
	{
		ID:             "minus",
		Name:           "マイナス星人",
		Desc:           "ひたすらマイナスなことばかり考えさせる。低めのローボールが得意。",
		PitchSpeedMod:  1.2,
		StrikeRate:     0.60,
		SwingAtStrike:  0.65,
		SwingAtBall:    0.20,
		CPUMissRate:    0.30,
		LowPitchesOnly: true,
		FlavorText:     "トボトボと自信なさげにスイングした...",
		PitchText:      "暗闇の底へ沈み込んでいくような低めスローボールを投げました。",
	},
	{
		ID:            "pokapoka",
		Name:          "ポカポカ星人",
		Desc:          "自覚なしに自分の頭をおもいっきり殴ってしまう。予測不能。",
		PitchSpeedMod: 0.9,
		StrikeRate:    0.50,
		SwingAtStrike: 0.85,
		SwingAtBall:   0.80,
		CPUMissRate:   0.45,
		Unpredictable: true,
		FlavorText:    "自分の頭をポカポカ殴りながら、無自覚に大振りした！",
		PitchText:     "どこに行くか全く分からないポカポカ魔球を投げました！",
	},
	{
		ID:            "tonton",
		Name:          "トントン星人",
		Desc:          "寝ているときに頭を指先でトントンしてくる。一定のリズムを刻む。",
		PitchSpeedMod: 0.95,
		StrikeRate:    0.60,
		SwingAtStrike: 0.80,
		SwingAtBall:   0.20,
		CPUMissRate:   0.15,
		Rhythmic:      true,
		FlavorText:    "トントンとリズムを取りながらコンパクトにスイングした！",
		PitchText:     "頭をトントン叩くような細かい上下のブレがある球を投げました。",
	},
	{
		ID:            "fukufuku",
		Name:          "服服星人",
		Desc:          "夜中に服を脱ぎ散らかし、その服を部屋中で探し回る。神出鬼没。",
		PitchSpeedMod: 1.05,
		StrikeRate:    0.50,
		SwingAtStrike: 0.75,
		SwingAtBall:   0.35,
		CPUMissRate:   0.28,
		ScatterPanner: true,
		FlavorText:    "服を探すようにバットを振り回した！",
		PitchText:     "脱ぎ散らかした服のように、音の聞こえる方向が二転三転する球を投げました！",
	},
	{
		ID:            "ooabare",
		Name:          "大暴れ星人",
		Desc:          "嫌なことを言われたとそこら中に八つ当たりする。怪力無双。",
		PitchSpeedMod: 0.75,
		StrikeRate:    0.60,
		SwingAtStrike: 0.95,
		SwingAtBall:   0.50,
		CPUMissRate:   0.40,
		RageMode:      true,
		FlavorText:    "怒り狂ってバットを大暴れさせ、物凄いスイングを見せた！",
		PitchText:     "八つ当たりするような豪速球を力一杯投げました！",
	},
	{
		ID:            "batabata",
		Name:          "お布団バタバタ星人",
		Desc:          "お布団の中で手足をバタバタさせている。落ち着きがない。",
		PitchSpeedMod: 0.85,
		StrikeRate:    0.55,
		SwingAtStrike: 0.85,
		SwingAtBall:   0.55,
		CPUMissRate:   0.25,
		FlutterSound:  true,
		FlavorText:    "手足をバタバタさせながら、何度も振るようなスイング！",
		PitchText:     "お布団をバタバタ叩くような小刻みなブレを伴って投げました！",
	},
	{
		ID:            "ofuton",
		Name:          "お布団星人",
		Desc:          "あったかい布団に誘い込み、太いベルトで拘束して眠らせようとする。",
		PitchSpeedMod: 1.5,
		StrikeRate:    0.40,
		SwingAtStrike: 0.40,
		SwingAtBall:   0.05,
		CPUMissRate:   0.20,
		HeavySleep:    true,
		FlavorText:    "半分居眠りしながら、のそっとスイングした...",
		PitchText:     "眠気を誘うような、極限までスローで重たい球を投げました...",
	},
	{
		ID:            "kangaroo",
		Name:          "カンガルー星人",
		Desc:          "無意識にパートナーの腕にしがみつく。インコースへの密着が得意。",
		PitchSpeedMod: 1.0,
		StrikeRate:    0.55,
		SwingAtStrike: 0.80,
		SwingAtBall:   0.20,
		CPUMissRate:   0.15,
		ClingIn:       true,
		FlavorText:    "しがみつくようなフォームでインコースを綺麗に捉えた！",
		PitchText:     "バッターの体にしがみつくような内角シュートを投げました！",
	},
	{
		ID:            "amaenbo",
		Name:          "アマエンボ星人",
		Desc:          "赤ちゃんになって甘えたくて仕方なくなる。泣き虫。",
		PitchSpeedMod: 1.25,
		StrikeRate:    0.65,
		SwingAtStrike: 0.60,
		SwingAtBall:   0.30,
		CPUMissRate:   0.35,
		CryBaby:       true,
		FlavorText:    "ふえぇん！と泣きそうになりながら弱々しくスイングした！",
		PitchText:     "へなへなとした、甘えるようなスローボールを投げました。",
	},
	{
		ID:            "haraheri",
		Name:          "腹減り星人",
		Desc:          "帰宅前に最寄りの飲食店に無理矢理連れていく。早食いでせっかち。",
		PitchSpeedMod: 0.80,
		StrikeRate:    0.65,
		SwingAtStrike: 0.90,
		SwingAtBall:   0.60,
		CPUMissRate:   0.22,
		RushedWindup:  true,
		FlavorText:    "早くご飯を食べに行きたそうに、超スピードで振り抜いた！",
		PitchText:     "せっかちでクイックモーションなストレートを投げました！",
	},
	{
		ID:            "dessert",
		Name:          "デザート星人",
		Desc:          "食後に何かしら甘いものを強要する。フレンチトーストが主食。",
		PitchSpeedMod: 1.0,
		StrikeRate:    0.50,
		SwingAtStrike: 0.95,
		SwingAtBall:   0.15,
		CPUMissRate:   0.10,
		SweetZone:     true,
		FlavorText:    "甘い球（真ん中ストライク）を逃さず、フレンチトースト並みに甘美なスイング！",
		PitchText:     "甘い香りが漂いそうな、打ち頃のスピードの球を投げました。",
	},
	{
		ID:            "card",
		Name:          "カード星人",
		Desc:          "限度額を考えずにどんどん無駄遣いさせようとする。散財スイング。",
		PitchSpeedMod: 0.9,
		StrikeRate:    0.55,
		SwingAtStrike: 0.88,
		SwingAtBall:   0.50,
		CPUMissRate:   0.20,
		SnoopyPouch:   true,
		FlavorText:    "限度額一杯までバットを振り回す、大盤振る舞いスイング！",
		PitchText:     "リボ払いのような、後から変化する軌道の球を投げました！",
	},
	{
		ID:            "okane",
		Name:          "お金星人",
		Desc:          "手持ちの現金を残さずすべて使い切らせる。全打席フルスイング。",
		PitchSpeedMod: 0.85,
		StrikeRate:    0.60,
		SwingAtStrike: 0.99,
		SwingAtBall:   0.70,
		CPUMissRate:   0.15,
		SpendAll:      true,
		FlavorText:    "余力を一切残さない、有り金をすべて叩き出すようなフルスイング！",
		PitchText:     "全財産を賭けたような渾身の全力ストレートを投げました！",
	},
	{
		ID:            "kowai_s",
		Name:          "怖い星人（Sサイズ）",
		Desc:          "無口だがジロッとにらみつけてプレッシャーをかけてくる星人。",
		PitchSpeedMod: 0.95,
		StrikeRate:    0.70,
		SwingAtStrike: 0.75,
		SwingAtBall:   0.10,
		CPUMissRate:   0.15,
		Glare:         true,
		FlavorText:    "無言のまま、こちらをジロッとにらみつけながらスイングした！",
		PitchText:     "にらみつけるような鋭いストレートを投げてきました。",
	},
	{
		ID:            "kowai_m",
		Name:          "怖い星人（Mサイズ）",
		Desc:          "タッチすると「なにすんねん」と怒り出す星人。",
		PitchSpeedMod: 0.90,
		StrikeRate:    0.60,
		SwingAtStrike: 0.80,
		SwingAtBall:   0.20,
		CPUMissRate:   0.18,
		GrumbleM:      true,
		FlavorText:    "「なにすんねん！」と怒りながらスイングしてきた！",
		PitchText:     "「なにすんねん！」と怒り混じりの勢いで投げました！",
	},
	{
		ID:            "kowai_l",
		Name:          "怖い星人（Lサイズ）",
		Desc:          "タッチすると「たかいたかーい」で抱え上げられる。超怪力。",
		PitchSpeedMod: 0.70,
		StrikeRate:    0.65,
		SwingAtStrike: 0.95,
		SwingAtBall:   0.15,
		CPUMissRate:   0.05,
		HeavyL:        true,
		FlavorText:    "「タッチすんなぁ！」と絶叫し、バットをブン回して持ち上げるようなスイング！",
		PitchText:     "「タッチすんなぁ！」と怒り狂う大迫力の超剛速球を投げました！",
	},
	{
		ID:            "lovelove",
		Name:          "ラブラブ星人",
		Desc:          "昼夜問わず営みを誘ってくる。ピンク色の妖艶な球筋。",
		PitchSpeedMod: 1.1,
		StrikeRate:    0.50,
		SwingAtStrike: 0.85,
		SwingAtBall:   0.35,
		CPUMissRate:   0.20,
		PinkAura:      true,
		FlavorText:    "妖艶なオーラを纏いながら情熱的にスイングした！",
		PitchText:     "くねくねと妖しく曲がる、ハートを描くような球を投げました。",
	},
}
